// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uykfnpbvqonfowzxxrmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5a2ZucGJ2cW9uZm93enh4cm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMjcwMTgsImV4cCI6MjA1MjYwMzAxOH0.i_C7QI19-J_A4pZ7IRsCatLSNnigec3X4v42GHa6ycY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);